@startuml
    title FULL PROCESS

    actor "Client (Mobile SDK/Web SDK)" as Client
    box "Merchant Application Area" #efefef
        participant "Application" as Server
        database "DB" as DB
        actor Operator
    end box
    participant "Third-party APIs" as API
    collections "Merchant System" as Bank
    participant "KYC Application" as KYC

    activate Server
        ref over Client, Server, DB, API : TWO-FACTOR AUTHENTICATION
        ref over Client, Server, DB, API, Bank : VERIFICATION PROCESS
        ref over Client, Server, DB : CALENDAR SYNCHRONIZATION PROCESS
        ref over Client, Server, DB, Operator : VIDEO CALL PROCESS
        ref over Client, Server, DB, Operator : CONTRACT SIGN PROCESS

        Server -[#green]-> Client : VERIFICATION PROCESS COMPLETED
        Server -[#gray]> Bank : send new verified user data pack
        activate Bank
            Bank -[#gray]-> Server : ok
        deactivate Bank
        Server -[#green]> KYC : synchronize success transaction
        activate KYC
            KYC -[#gray]-> Server : ok
        deactivate KYC
    deactivate Server
@enduml